data:
  cache_dir: null
  clean_old_caches: true
  data_dir: full_data
  force_rebuild_cache: false
  max_files: null
  memory_cache_size: 2000
  num_workers: 16
  sequence_length: 512
  stride: 256
  train_split: 0.9
  use_memory_cache: true
  warmup_cache: true
model:
  attn_dropout: 0.1
  composer_embedding_dim: 128
  condition_dim: 128
  dim: 512
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.1
  ff_mult: 4
  max_seq_len: 2048
  num_composers: 16
  perf_decoder_depth: 4
  perf_decoder_heads: 8
  score_encoder_depth: 4
  score_encoder_heads: 8
  tempo_fusion_type: concat
  tempo_hidden_dim: 256
  tempo_predictor_type: multiscale
  token_emb_mode: cat
  use_composer_conditioning: true
  use_musical_position: true
  use_tempo_prediction: true
trainer:
  eval_every: 1
  experiment_name: sustain_classify_20250815_073720
  min_delta: 1.0e-06
  patience: 15
  save_dir: ./check/sustain_classify_20250815_073720
  save_every: 5
  use_wandb: false
  wandb_project: score_performer
training:
  accumulation_steps: 1
  adam_betas:
  - 0.9
  - 0.95
  adam_eps: 1.0e-08
  auto_adjust_lr: true
  batch_size: 128
  final_predicted_ratio: 0.5
  grad_clip_value: 0.5
  learning_rate: 5e-5
  lr_factor: 0.5
  lr_patience: 5
  max_epochs: 500
  min_lr: 1.0e-06
  mixed_precision: true
  optimizer: adamw
  scheduler_type: warmup_cosine
  seed: 42
  start_predicted_epoch: 150
  tempo_loss_weight: 1
  tempo_schedule_type: linear
  use_scheduler: true
  warmup_epochs: 20
  weight_decay: 0.01
